### ISSUE TITLE
CORS error

### ISSUE THREAD

**Issue by darshiljain9** [sneha-at-hub/FreshFarm#2]
Please configure CORS to make the live site functional.

**Comment by sneha-at-hub** [comment]
My backend hosting's free credit has been used up, so the site is only functional for 15 days each month. If you'd like to give it a try, you can clone the repository and run it locally and test all the features without any downtime.  Make sure to update the API path in the code from the Netlify site URL to 'http://localhost:{your_nodejs_port}/'.

**Comment by darshiljain9** [comment]
I can't access it as I don't have database. Can you add exported file in the repo?  And would you like to push the project ahead or planning to drop it out? I am asking because I found it impressive and would like to contribute in it.

**Comment by sneha-at-hub** [comment]
I've added the exported database file to the repository. As for the project, I definitely plan to push it ahead. There's still a lot to explore and improve. Your contribution would be greatly appreciated!
